name: Run Eren Bot by Ali

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: |
          npm run start &  
          while true; do
            echo "Bot is running..."
            sleep 60
          done
